[tool.poetry]
name = "terminaide"
version = "0.0.0"
description = "Serve Python CLI applications in the browser using ttyd"
authors = ["Alex Basile <basileaw@gmail.com>"]
packages = [{ include = "terminaide" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.104.0"
uvicorn = ">=0.24.0"
jinja2 = ">=3.1.2"
httpx = ">=0.25.0"
websockets = ">=12.0"
pydantic = ">=2.4.2"
chatline = { git = "https://github.com/anotherbazeinthewall/chatline-interface.git" }

[tool.poetry.group.test-server.dependencies]
bs4 = ">=0.0.2"
requests = ">=2.32.3"
rich = "*"

[tool.poetry.group.dev.dependencies]
pyyaml = "*"
boto3 = "*"
botocore = "*"

[tool.poe.tasks]
serve-local = "python example/server.py"
serve-container = "docker compose up --build"
